env:
  global:
    - secure: "QvFzzFWmfpWFam2wHa66dFmjs7vmkYN6sGMPqj/s9H9sU0evmTASt1uX9Gr0isi8BpZ9pseq+F6L/lDOv8xpA3L8RQ3o41orIDMDkGjybIju4VNQmy+V5/yjGDfDUXGV6MGIlqnWg+5dhn2WvzHJYF1RMI/DEA/VOGeHW/nccyqOgFmV65JQLPkr/SzYGd92pYzWcW+hsij5jEl7Goi3acJfl4ag3e2cw9mro0nR9uKVcs5oGVhTViau/Ju5Wig4prYALUh5WFGLNRskiywYP4O53K3TtZ0WXwoE7VyfVZTMEIXNu3n/8wT5pCKf7KIUO1R0tFRdunHhIu2ZdZTlzjc3Fgl0IWTM5k+C7t6JBQHBZC6HGIolrkekNjsrkjpOdW+MrXvB7vncxjIERCaQTg1b1FMz7B20iYTnIg42N65xsD9J0d9jPziYElHfAQCthweOkdkX1IlII71Q6RQ91v+EvKPGEgCItpj2oR3vNZ4aUZCIoJXX1f1B6S0SP1wZksO3vog/CBPOdqmD/8fnoQqYARWTpxYP0pGxCWRnyYt9aq37xV1dvotW2Z4WZ3Xww9k4/5LO7S43q+wtslvQVCrh5mBtQlliNZzjA1tYJ4p/GgUjrL+faOwBFNmIeQSB4fLAwX+pL2gVnuf1uEbx89LMMus7IMkJueKIRQs8Kt0="
    - GIT_DEPLOY_DIR=public
    - GIT_DEPLOY_BRANCH=gh-pages
    - GIT_DEPLOY_USERNAME="Travis CI"
    - GIT_DEPLOY_EMAIL=michael@mitchtech.net

branches:
  only:
    - master

install:
  - rm -rf public || exit 0

script:
  - binaries/hugo

after_success:
  - cp .travis.yml public
  - bash deploy.sh